### ISSUE TITLE
api useTodos is not working with upgrade of swr

### ISSUE THREAD

**Issue by ghwrivas** [railwayapp-templates/nextjs-prisma#3]
Hi, today I created a new project from railway platform using this template but when I was trying to test the app, useTodos did not to get the data.

I downgrade swr to 0.4.2 version and useTodos worked correctly.

**Comment by otowa1** [comment]
The same phenomenon occurs.

The data itself seems to be registered correctly in the database.

**Comment by Seligmann** [comment]
This change fixed the issue for me as well. Bumping this in hopes of a merge so that other new users such as myself don't run into this.

**Comment by onjun660** [comment]
The procedure on the first page of the document doesn't work for over a month and we get no feedback. This seems to be the problem.

**Comment by jtannady** [comment]
omg I'm also experiencing this issue! So glad I'm not alone!
